#!/usr/bin/env python3
"""
Train and evaluate HNSCC survival models: TCGA discovery (training) → CPTAC validation (assessment of performance).

Strategies for feature selection (involving both RNA and SCNA features):

1. Block-Constrained Univariate Feature Selection: Force top N RNA + top M SCNA (min M=4)
   Uses univariate C-index ranking for the RNA and SCNA features to assess which ones are associated with survival

2. Priority-Lasso: Hierarchical fitting that preserves block contributions
   Clinical → RNA → SCNA, each block explains residual variance; We use this order due to the high predictive value of clinical and RNA features

3. Late Fusion Ensemble: Separate models combined
   An RSF_RNA model and RSF_SCNA model are trained on their respective data types. Their predictions are combined via weighted averaging

4. IPF-Lasso Style: Different regularization per block
   Lower relative penalty on SCNA to encourage inclusion

5. Stability Selection: Bootstrap selection on each block
   Performs a variety of boostraps on subsets of both the RNA and SCNA datasets. Features stable in >50% of bootstraps from both RNA and SCNA are kept 

Inputs:
    --train-data: TCGA discovery CSV, generated via the data processing pipeline.
    --test-data: CPTAC validation CSV, also generated by the processing pipeline.
    --output: Parent directory for timestamped model outputs.

Outputs:
    all_results.csv, best_model_features.csv, selected_rna_features.csv,
    selected_scna_features.csv, and top20_scna_features.csv.

Example Run:
    python scripts/training/train_survival_models.py \
        --train-data real_data/TCGA_Discovery_Harmonized_Full_Data.csv \
        --test-data real_data/CPTAC_Validation_Harmonized_Full_Data.csv \
        --output results/model_runs \
        --mode block \
        --n-jobs 1 \
        --seed 42
"""

# Import Dependencies, Install anything not present
import argparse
import os
import numpy as np
import pandas as pd
import warnings
from datetime import datetime
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sksurv.linear_model import CoxnetSurvivalAnalysis
from sksurv.ensemble import RandomSurvivalForest, GradientBoostingSurvivalAnalysis
from sksurv.metrics import concordance_index_censored
import importlib



np = None
pd = None
StandardScaler = None
CoxnetSurvivalAnalysis = None
RandomSurvivalForest = None
concordance_index_censored = None

warnings.filterwarnings("ignore")


def load_modeling_dependencies():
    """Import heavy scientific dependencies after argparse so --help always works."""
    global np, pd, StandardScaler, CoxnetSurvivalAnalysis
    global RandomSurvivalForest, concordance_index_censored

    np = importlib.import_module("numpy")
    pd = importlib.import_module("pandas")
    StandardScaler = importlib.import_module("sklearn.preprocessing").StandardScaler
    CoxnetSurvivalAnalysis = importlib.import_module(
        "sksurv.linear_model"
    ).CoxnetSurvivalAnalysis
    RandomSurvivalForest = importlib.import_module(
        "sksurv.ensemble"
    ).RandomSurvivalForest
    concordance_index_censored = importlib.import_module(
        "sksurv.metrics"
    ).concordance_index_censored


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train TCGA-discovery and CPTAC-validation HNSCC survival models"
    )
    parser.add_argument("--train-data", required=True, help="Harmonized TCGA discovery CSV")
    parser.add_argument("--test-data", required=True, help="Harmonized CPTAC validation CSV")
    parser.add_argument("--output", required=True, help="Parent output directory")
    parser.add_argument("--n-jobs", type=int, default=1, help="Parallel jobs for RSF models")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument(
        "--mode",
        choices=["block", "extended", "full"],
        default="block",
        help=(
            "Model set to run. `block` runs the fast block-constrained RSF sweep; "
            "`extended` also runs priority-lasso, late-fusion, and IPF-style models; "
            "`full` additionally runs slow bootstrap stability selection."
        ),
    )
    return parser.parse_args()


# Preprocessing and Input Validation Helpers


def ensure_columns(df, required_cols, label):
    """Fail early with a clear message if required columns are missing."""
    missing = [col for col in required_cols if col not in df.columns]
    if missing:
        raise ValueError(f"{label} is missing required columns: {missing}")


def coerce_event_column(series):
    """Convert common OS_event encodings to bool without treating string '0' as True."""
    def convert(value):
        if pd.isna(value):
            return False
        if isinstance(value, (bool, np.bool_)):
            return bool(value)
        if isinstance(value, (int, float, np.integer, np.floating)):
            return bool(int(value))
        value_str = str(value).strip().lower()
        if value_str in {"1", "true", "t", "yes", "y", "dead", "deceased", "event"}:
            return True
        if value_str in {"0", "false", "f", "no", "n", "alive", "censored"}:
            return False
        raise ValueError(f"Unrecognized OS_event value: {value!r}")

    return series.map(convert).astype(bool)


def common_omic_columns(train_df, test_df, prefix):
    """Return train-ordered omics columns that also exist in the test cohort."""
    train_cols = [c for c in train_df.columns if c.startswith(prefix)]
    test_cols = set(c for c in test_df.columns if c.startswith(prefix))
    common_cols = [c for c in train_cols if c in test_cols]
    dropped = len(train_cols) - len(common_cols)
    if dropped:
        print(f"  [{prefix}] Dropping {dropped} train-only features not present in test data")
    if not common_cols:
        raise ValueError(f"No shared {prefix} features found between train and test data")
    return common_cols


def impute_and_scale_block(train_df, test_df, cols, label):
    """Numeric coercion, train-median imputation, and standard scaling for one feature block."""
    if not cols:
        raise ValueError(f"No columns supplied for {label} feature block")

    X_train = train_df[cols].apply(pd.to_numeric, errors="coerce").to_numpy(
        dtype=float,
        copy=True,
    )
    X_test = test_df[cols].apply(pd.to_numeric, errors="coerce").to_numpy(
        dtype=float,
        copy=True,
    )
    col_means = np.nanmean(X_train, axis=0)
    col_means = np.where(np.isnan(col_means), 0, col_means)
    train_missing = np.isnan(X_train)
    test_missing = np.isnan(X_test)
    if train_missing.any():
        X_train[train_missing] = np.take(col_means, np.where(train_missing)[1])
    if test_missing.any():
        X_test[test_missing] = np.take(col_means, np.where(test_missing)[1])
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    print(f"  {label} features: {len(cols)}")
    return X_train_scaled, X_test_scaled


def top_feature_indices(scores, requested_n):
    """Select up to requested_n feature indices, ordered from strongest to weakest."""
    requested_n = min(int(requested_n), len(scores))
    if requested_n <= 0:
        return np.array([], dtype=int)
    return np.argsort(scores)[-requested_n:][::-1]


# Clinical Harmonization

def harmonize_clinical_data(train_df, test_df):
    """Apply all harmonization steps"""

    train_df["Age"] = pd.to_numeric(train_df["Age"], errors="coerce")
    test_df["Age"] = pd.to_numeric(test_df["Age"], errors="coerce")
    if train_df["Age"].median(skipna=True) > 1000:
        print("  [Age] Converting TCGA from days to years")
        train_df["Age"] = train_df["Age"] / 365.25
    train_age_median = train_df["Age"].median(skipna=True)
    train_df["Age"] = train_df["Age"].fillna(train_age_median)
    test_df["Age"] = test_df["Age"].fillna(train_age_median)

    for df in [train_df, test_df]:
        df["Gender"] = df["Gender"].astype(str).str.lower().str.strip()
        df["Gender"] = df["Gender"].map(
            lambda x: "Male"
            if "male" in x and "female" not in x
            else "Female"
            if "female" in x
            else "Unknown"
        )

    def simplify_stage(s):
        s = str(s).upper().replace("STAGE", "").strip()
        if s.startswith("IV"):
            return "IV"
        elif s.startswith("III"):
            return "III"
        elif s.startswith("II"):
            return "II"
        elif s.startswith("I"):
            return "I"
        else:
            return "Unknown"

    train_df["Stage"] = train_df["Stage"].apply(simplify_stage)
    test_df["Stage"] = test_df["Stage"].apply(simplify_stage)

    def simplify_t(s):
        s = str(s).upper().replace("P", "").strip()
        for t in ["T4", "T3", "T2", "T1", "T0"]:
            if s.startswith(t):
                return t
        return "TX"

    train_df["T_Stage"] = train_df["T_Stage"].apply(simplify_t)
    test_df["T_Stage"] = test_df["T_Stage"].apply(simplify_t)

    def simplify_n(s):
        s = str(s).upper().replace("P", "").strip()
        for n in ["N3", "N2", "N1", "N0"]:
            if s.startswith(n):
                return n
        return "NX"

    train_df["N_Stage"] = train_df["N_Stage"].apply(simplify_n)
    test_df["N_Stage"] = test_df["N_Stage"].apply(simplify_n)

    def simplify_grade(s):
        s = str(s).upper()
        if "G1" in s or "WELL" in s:
            return "G1"
        elif "G2" in s or "MODERATE" in s:
            return "G2"
        elif "G3" in s or "POOR" in s:
            return "G3"
        else:
            return "GX"

    train_df["Grade"] = train_df["Grade"].apply(simplify_grade)
    test_df["Grade"] = test_df["Grade"].apply(simplify_grade)

    def simplify_alcohol(s):
        s = str(s).lower()
        if "yes" in s or ("consum" in s and "non" not in s):
            return "Yes"
        elif "no" in s or "non-drinker" in s or "lifelong" in s:
            return "No"
        else:
            return "Unknown"

    train_df["Alcohol_History"] = train_df["Alcohol_History"].apply(simplify_alcohol)
    test_df["Alcohol_History"] = test_df["Alcohol_History"].apply(simplify_alcohol)

    train_df["Pack_Years"] = pd.to_numeric(train_df["Pack_Years"], errors="coerce")
    test_df["Pack_Years"] = pd.to_numeric(test_df["Pack_Years"], errors="coerce")
    median_py = train_df["Pack_Years"].median(skipna=True)
    if pd.isna(median_py):
        median_py = 0
    train_df["Pack_Years"] = train_df["Pack_Years"].fillna(median_py)
    test_df["Pack_Years"] = test_df["Pack_Years"].fillna(median_py)

    return train_df, test_df


def process_clinical_features(train_df, test_df, clinical_cols):
    """Process clinical features with consistent encoding"""
    numeric_cols = ["Age", "Pack_Years"]
    categorical_cols = [c for c in clinical_cols if c not in numeric_cols]

    X_train_num = train_df[numeric_cols].values.astype(float)
    X_test_num = test_df[numeric_cols].values.astype(float)
    scaler = StandardScaler()
    X_train_num = scaler.fit_transform(X_train_num)
    X_test_num = scaler.transform(X_test_num)

    feature_names = list(numeric_cols)
    X_train_cat_list = []
    X_test_cat_list = []

    for col in categorical_cols:
        all_cats = sorted(set(train_df[col].unique()) | set(test_df[col].unique()))
        for cat in all_cats[1:]:
            X_train_cat_list.append((train_df[col] == cat).astype(float).values)
            X_test_cat_list.append((test_df[col] == cat).astype(float).values)
            feature_names.append(f"{col}_{cat}")

    if X_train_cat_list:
        X_train_cat = np.column_stack(X_train_cat_list)
        X_test_cat = np.column_stack(X_test_cat_list)
        X_train_clin = np.hstack([X_train_num, X_train_cat])
        X_test_clin = np.hstack([X_test_num, X_test_cat])
    else:
        X_train_clin = X_train_num
        X_test_clin = X_test_num

    return X_train_clin, X_test_clin, feature_names


def univariate_cindex_scores(X, y):
    """Calculate univariate C-index deviation for all features."""
    event = y["event"]
    time = y["time"]
    n_features = X.shape[1]
    scores = np.zeros(n_features)

    for j in range(n_features):
        try:
            x_j = X[:, j]
            if np.std(x_j) < 1e-10:
                continue
            c_idx, _, _, _, _ = concordance_index_censored(event, time, x_j)
            scores[j] = abs(c_idx - 0.5)
        except Exception:
            pass

    return scores


# Stability Selection (Per-Block)


def stability_selection_per_block(X, y, n_bootstrap=100, top_k=50, seed=42):
    """
    Bootstrap-based stability selection for a single block.
    Returns selection probability for each feature.
    """
    np.random.seed(seed)
    n_samples, n_features = X.shape
    selection_counts = np.zeros(n_features)

    event = y["event"]
    time = y["time"]

    for b in range(n_bootstrap):
        idx = np.random.choice(n_samples, size=n_samples, replace=True)
        X_boot = X[idx]
        event_boot = event[idx]
        time_boot = time[idx]

        scores = np.zeros(n_features)
        for j in range(n_features):
            try:
                x_j = X_boot[:, j]
                if np.std(x_j) < 1e-10:
                    continue
                c_idx, _, _, _, _ = concordance_index_censored(
                    event_boot, time_boot, x_j
                )
                scores[j] = abs(c_idx - 0.5)
            except Exception:
                pass

        top_idx = np.argsort(scores)[-top_k:]
        selection_counts[top_idx] += 1

    return selection_counts / n_bootstrap


# Hyperparameter Tuning for the RandomSurvivalForests Model (Aggressive)


def tune_rsf_aggressive(X_train, y_train, n_jobs=4, seed=42):
    """
    Tune RSF with aggressive regularization.
    Uses OOB score with overfitting penalty.
    """
    param_configs = [
        # Very aggressive (v6 best was similar)
        {"n_estimators": 300, "min_samples_split": 45, "min_samples_leaf": 35,
         "max_features": 0.15, "max_depth": 3},
        {"n_estimators": 300, "min_samples_split": 50, "min_samples_leaf": 40,
         "max_features": 0.15, "max_depth": 3},
        {"n_estimators": 400, "min_samples_split": 50, "min_samples_leaf": 40,
         "max_features": 0.2, "max_depth": 3},
        # Even more aggressive
        {"n_estimators": 300, "min_samples_split": 50, "min_samples_leaf": 45,
         "max_features": 0.1, "max_depth": 2},
        {"n_estimators": 400, "min_samples_split": 55, "min_samples_leaf": 50,
         "max_features": 0.15, "max_depth": 2},
    ]

    best_adjusted = -np.inf
    best_model = None
    best_params = None

    for params in param_configs:
        try:
            model = RandomSurvivalForest(
                n_estimators=params["n_estimators"],
                min_samples_split=params["min_samples_split"],
                min_samples_leaf=params["min_samples_leaf"],
                max_features=params["max_features"],
                max_depth=params["max_depth"],
                oob_score=True,
                n_jobs=n_jobs,
                random_state=seed,
            )
            model.fit(X_train, y_train)

            oob_score = model.oob_score_
            train_c = model.score(X_train, y_train)
            gap = train_c - oob_score

            # Penalize overfitting
            adjusted = oob_score - 0.3 * gap

            if adjusted > best_adjusted:
                best_adjusted = adjusted
                best_model = model
                best_params = params

        except Exception as exc:
            print(f"    RSF parameter set failed: {exc}")
            continue

    return best_model, best_params


def write_model_outputs(
    output_dir,
    results,
    all_models,
    clin_names,
    rna_cols,
    cnv_cols,
    rna_scores,
    cnv_scores,
    cnv_stability=None,
):
    """Write model summary and feature tables for completed experiments."""
    print("\n" + "=" * 70)
    print("FINAL RESULTS")
    print("=" * 70)

    results_df = pd.DataFrame(results)
    if results_df.empty:
        print("No models completed successfully; writing empty results table.")
        results_df.to_csv(os.path.join(output_dir, "all_results.csv"), index=False)
        return

    results_df = results_df.sort_values("Test_C", ascending=False)
    print("\n--- ALL RESULTS (sorted by Test C-index) ---")
    print(results_df.to_string(index=False))

    print("\n" + "-" * 50)
    print("PROMISING MODELS:")
    print("  (>= 4 SCNA features AND Test C-index >= 0.6448)")
    print("-" * 50)

    qualifying_models = results_df[
        (results_df["N_SCNA"] >= 4) & (results_df["Test_C"] >= 0.6448)
    ]

    if len(qualifying_models) > 0:
        print(qualifying_models.to_string(index=False))
        best = qualifying_models.iloc[0]
        print(f"\nBEST MODEL: {best['Experiment']} ({best['Config']})")
        print(f"   Test C-index: {best['Test_C']:.4f}")
        print(
            f"   Features: {best['N_Clinical']} clinical + "
            f"{best['N_RNA']} RNA + {best['N_SCNA']} SCNA"
        )
    else:
        print("\nNo models met both criteria (>=4 SCNA and >=0.6448 C-index)")
        best = results_df.iloc[0]
        print(
            f"   Best overall: {best['Experiment']} ({best['Config']}): "
            f"Test C = {best['Test_C']:.4f}, {best['N_SCNA']} SCNA"
        )

    results_df.to_csv(os.path.join(output_dir, "all_results.csv"), index=False)
    selected_summary_row = qualifying_models.iloc[0] if len(qualifying_models) > 0 else results_df.iloc[0]

    def infer_model_key(row):
        experiment = row["Experiment"]
        config = row["Config"]
        if experiment == "Block_Constrained":
            return f"Block_{config}"
        if experiment == "Priority_Lasso":
            return f"PriorityLasso_{config}"
        if experiment == "Late_Fusion":
            return f"LateFusion_alpha{str(config).split('alpha')[-1]}"
        if experiment == "IPF_Style":
            return f"IPF_boost{str(config).split('boost')[-1]}"
        if experiment == "Stability_MultiBlock":
            return "Stability_MultiBlock"
        return None

    best_key = infer_model_key(selected_summary_row)
    if best_key not in all_models:
        print(f"Warning: could not find stored model for feature export: {best_key}")
    else:
        best_model_info = all_models[best_key]
        feature_df = pd.DataFrame({
            "feature": best_model_info["features"],
            "type": ["clinical"] * len(clin_names)
                    + ["RNA"] * len(best_model_info["rna_features"])
                    + ["SCNA"] * len(best_model_info["scna_features"]),
        })
        feature_df.to_csv(os.path.join(output_dir, "best_model_features.csv"), index=False)

        rna_feature_df = pd.DataFrame({
            "feature": best_model_info["rna_features"],
            "cindex_deviation": [rna_scores[rna_cols.index(f)] for f in best_model_info["rna_features"]],
        }).sort_values("cindex_deviation", ascending=False)
        rna_feature_df.to_csv(os.path.join(output_dir, "selected_rna_features.csv"), index=False)

        scna_feature_df = pd.DataFrame({
            "feature": best_model_info["scna_features"],
            "cindex_deviation": [cnv_scores[cnv_cols.index(f)] for f in best_model_info["scna_features"]],
        }).sort_values("cindex_deviation", ascending=False)
        scna_feature_df.to_csv(os.path.join(output_dir, "selected_scna_features.csv"), index=False)

        print(f"\nFeature lists saved to: {output_dir}")

    top_scna_indices = top_feature_indices(cnv_scores, 20)
    if cnv_stability is None:
        stability_values = [np.nan] * len(top_scna_indices)
    else:
        stability_values = [cnv_stability[i] for i in top_scna_indices]
    top_scna_df = pd.DataFrame({
        "feature": [cnv_cols[i] for i in top_scna_indices],
        "cindex_deviation": [cnv_scores[i] for i in top_scna_indices],
        "stability": stability_values,
    })
    top_scna_df.to_csv(os.path.join(output_dir, "top20_scna_features.csv"), index=False)

    print(f"\nResults saved to: {output_dir}")


# Main

def main():
    args = parse_args()
    load_modeling_dependencies()
    np.random.seed(args.seed)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir = os.path.join(args.output, f"run_v7_{timestamp}")
    os.makedirs(output_dir, exist_ok=True)

    print("=" * 70)
    print("Head and Neck Squamous Cell Carcinoma Survival Prediction with RNA and SCNA Features")
    print("=" * 70)
    print(f"Output: {output_dir}")
    print(f"Mode: {args.mode}")
    print("\n5 Potential Feature Selection Methods:")
    print("  1. Block-Constrained Feature Selection (RNA + SCNA)")
    print("  2. Priority-Lasso (Hierarchical)")
    print("  3. Late Fusion Ensemble (RSF_RNA + RSF_SCNA)")
    print("  4. IPF-LASSO Style (Different penalties)")
    print("  5. Stability-Selected Multi-Block (only with --mode full)")

    # Load Data
    print("\n" + "=" * 70)
    print("Loading Data")
    print("=" * 70)

    train_df = pd.read_csv(args.train_data)
    test_df = pd.read_csv(args.test_data)

    required_cols = [
        "Age", "Gender", "Stage", "T_Stage", "N_Stage",
        "Grade", "Alcohol_History", "Pack_Years", "OS_days", "OS_event",
    ]
    ensure_columns(train_df, required_cols, "Training data")
    ensure_columns(test_df, required_cols, "Test data")

    train_df, test_df = harmonize_clinical_data(train_df, test_df)

    train_df["OS_days"] = pd.to_numeric(train_df["OS_days"], errors="coerce")
    test_df["OS_days"] = pd.to_numeric(test_df["OS_days"], errors="coerce")
    train_df["OS_event"] = coerce_event_column(train_df["OS_event"])
    test_df["OS_event"] = coerce_event_column(test_df["OS_event"])
    train_df = train_df.dropna(subset=["OS_days"]).copy()
    test_df = test_df.dropna(subset=["OS_days"]).copy()
    train_df = train_df[train_df["OS_days"] > 0].copy()
    test_df = test_df[test_df["OS_days"] > 0].copy()

    y_train = np.array(
        list(zip(train_df["OS_event"], train_df["OS_days"])),
        dtype=[("event", bool), ("time", float)],
    )
    y_test = np.array(
        list(zip(test_df["OS_event"], test_df["OS_days"])),
        dtype=[("event", bool), ("time", float)],
    )
    event_train = train_df["OS_event"].values
    n_events = event_train.sum()

    print(f"  Train: {len(train_df)} samples, {n_events} events ({n_events / len(train_df):.1%})")
    print(f"  Test: {len(test_df)} samples, {test_df['OS_event'].sum()} events ({test_df['OS_event'].mean():.1%})")

    # Prepare Features
    print("\n" + "=" * 70)
    print("Preparing Features")
    print("=" * 70)

    clinical_cols = [
        "Age", "Gender", "Stage", "T_Stage", "N_Stage",
        "Grade", "Alcohol_History", "Pack_Years",
    ]
    rna_cols = common_omic_columns(train_df, test_df, "RNA_")
    cnv_cols = common_omic_columns(train_df, test_df, "CNV_")

    # Process clinical features
    X_train_clin, X_test_clin, clin_names = process_clinical_features(
        train_df, test_df, clinical_cols
    )
    print(f"  Clinical features: {len(clin_names)}")

    # Process RNA and CNV/SCNA blocks with train-only imputation/scaling
    X_train_rna_scaled, X_test_rna_scaled = impute_and_scale_block(
        train_df, test_df, rna_cols, "RNA"
    )
    X_train_cnv_scaled, X_test_cnv_scaled = impute_and_scale_block(
        train_df, test_df, cnv_cols, "CNV/SCNA"
    )

    # Calculate univariate scores for each block
    print("\n  Calculating univariate C-index scores...")
    rna_scores = univariate_cindex_scores(X_train_rna_scaled, y_train)
    cnv_scores = univariate_cindex_scores(X_train_cnv_scaled, y_train)

    # Report top features from each block
    top_rna_idx = top_feature_indices(rna_scores, 10)
    top_cnv_idx = top_feature_indices(cnv_scores, 10)

    print("\n  Top 10 RNA features by C-index deviation:")
    for i, idx in enumerate(top_rna_idx):
        print(f"    {i+1}. {rna_cols[idx]}: {rna_scores[idx]:.4f}")

    print("\n  Top 10 SCNA features by C-index deviation:")
    for i, idx in enumerate(top_cnv_idx):
        print(f"    {i+1}. {cnv_cols[idx]}: {cnv_scores[idx]:.4f}")

    results = []
    all_models = {}

    # Experiment 1: Block-Constrained Feature Selection
    print("\n" + "=" * 70)
    print("Experiment 1: Block-Constrained Feature Selection")
    print("=" * 70)
    print("  Strategy: Force top N RNA + top M SCNA (minimum M=4)")

    # Test different combinations while ensuring at least 4 SCNA
    block_configs = [
        (70, 4),   # 70 RNA + 4 SCNA = 74 omics features
        (65, 6),   # 65 RNA + 6 SCNA = 71 omics features
        (60, 8),   # 60 RNA + 8 SCNA = 68 omics features
        (55, 10),  # 55 RNA + 10 SCNA = 65 omics features
        (75, 4),   # 79 omics features
        (70, 6),   # Balanced
        (65, 8),   # More SCNA weight
    ]

    for n_rna, n_cnv in block_configs:
        print(f"\n  [Block-Constrained: {n_rna} RNA + {n_cnv} SCNA]")

        # Select top features from each block
        top_rna_idx = top_feature_indices(rna_scores, n_rna)
        top_cnv_idx = top_feature_indices(cnv_scores, n_cnv)

        # Get selected feature names
        selected_rna = [rna_cols[i] for i in top_rna_idx]
        selected_cnv = [cnv_cols[i] for i in top_cnv_idx]
        n_rna_actual = len(selected_rna)
        n_cnv_actual = len(selected_cnv)

        # Combine features
        X_train_sel = np.hstack([
            X_train_clin,
            X_train_rna_scaled[:, top_rna_idx],
            X_train_cnv_scaled[:, top_cnv_idx]
        ])
        X_test_sel = np.hstack([
            X_test_clin,
            X_test_rna_scaled[:, top_rna_idx],
            X_test_cnv_scaled[:, top_cnv_idx]
        ])

        feature_names_sel = clin_names + selected_rna + selected_cnv

        # Train RSF
        model, params = tune_rsf_aggressive(X_train_sel, y_train, args.n_jobs, args.seed)

        if model is None:
            print("    Failed to train model")
            continue

        oob_c = model.oob_score_
        train_c = model.score(X_train_sel, y_train)
        test_c = model.score(X_test_sel, y_test)

        print(f"    OOB: {oob_c:.4f}, Train: {train_c:.4f}, Test: {test_c:.4f}")
        print(f"    Total features: {len(feature_names_sel)} ({len(clin_names)} clin + {n_rna} RNA + {n_cnv} SCNA)")

        results.append({
            "Experiment": "Block_Constrained",
            "Config": f"RNA{n_rna_actual}_SCNA{n_cnv_actual}",
            "N_Clinical": len(clin_names),
            "N_RNA": n_rna_actual,
            "N_SCNA": n_cnv_actual,
            "N_Total": len(feature_names_sel),
            "OOB_C": oob_c,
            "Train_C": train_c,
            "Test_C": test_c,
        })

        all_models[f"Block_RNA{n_rna_actual}_SCNA{n_cnv_actual}"] = {
            "model": model,
            "X_test": X_test_sel,
            "features": feature_names_sel,
            "rna_features": selected_rna,
            "scna_features": selected_cnv,
        }

    if args.mode == "block":
        print("\nSkipping extended experiments; use --mode extended or --mode full to run them.")
        write_model_outputs(
            output_dir,
            results,
            all_models,
            clin_names,
            rna_cols,
            cnv_cols,
            rna_scores,
            cnv_scores,
        )
        return

    # Experiment 2: Priority-Lasso (Hierarchical)
   
    print("\n" + "=" * 70)
    print("Experiment 2: Priority-Lasso (Hierarchical Fitting)")
    print("=" * 70)
    print("  Strategy: Clinical → RNA → SCNA (each subsequent one explains the residual variance from the clinical predictions)")

    # Step 1: Fit on Clinical (unpenalized or very low penalty)
    print("\n  Step 1: Fitting on Clinical features...")
    try:
        model_clin = CoxnetSurvivalAnalysis(
            l1_ratio=0.01,  # Near Ridge
            alpha_min_ratio=0.1,
            max_iter=100000,
            fit_baseline_model=True,
        )
        model_clin.fit(X_train_clin, y_train)
        pred_clin_train = model_clin.predict(X_train_clin)
        pred_clin_test = model_clin.predict(X_test_clin)
        clin_test_c = model_clin.score(X_test_clin, y_test)
        print(f"    Clinical-only Test C-index: {clin_test_c:.4f}")
    except Exception as e:
        print(f"    Clinical model failed: {e}")
        pred_clin_train = np.zeros(len(train_df))
        pred_clin_test = np.zeros(len(test_df))
        clin_test_c = 0.5

    # Step 2: Fit on RNA with Clinical predictions as offset
    print("\n  Step 2: Fitting on RNA features (with Clinical offset)...")

    # Select top RNA features
    n_rna_priority = 50
    top_rna_idx = top_feature_indices(rna_scores, n_rna_priority)
    X_train_rna_sel = X_train_rna_scaled[:, top_rna_idx]
    X_test_rna_sel = X_test_rna_scaled[:, top_rna_idx]

    try:
        model_rna = CoxnetSurvivalAnalysis(
            l1_ratio=0.9,
            alpha_min_ratio=0.01,
            max_iter=100000,
            fit_baseline_model=True,
        )
        # Combine clinical features with RNA for this step
        X_train_clin_rna = np.hstack([X_train_clin, X_train_rna_sel])
        X_test_clin_rna = np.hstack([X_test_clin, X_test_rna_sel])
        model_rna.fit(X_train_clin_rna, y_train)
        pred_rna_train = model_rna.predict(X_train_clin_rna)
        pred_rna_test = model_rna.predict(X_test_clin_rna)
        rna_test_c = model_rna.score(X_test_clin_rna, y_test)
        print(f"    Clinical+RNA Test C-index: {rna_test_c:.4f}")
    except Exception as e:
        print(f"    RNA model failed: {e}")
        pred_rna_train = pred_clin_train
        pred_rna_test = pred_clin_test
        rna_test_c = clin_test_c

    # Step 3: Fit on SCNA with Clinical + RNA predictions as offset
    print("\n  Step 3: Fitting on SCNA features (with Clinical+RNA offset)...")

    # Select top SCNA features (minimum 4)
    for n_scna_priority in [10, 8, 6, 4]:
        top_cnv_idx = top_feature_indices(cnv_scores, n_scna_priority)
        X_train_cnv_sel = X_train_cnv_scaled[:, top_cnv_idx]
        X_test_cnv_sel = X_test_cnv_scaled[:, top_cnv_idx]

        try:
            # Full model: Clinical + RNA + SCNA
            X_train_full = np.hstack([X_train_clin, X_train_rna_sel, X_train_cnv_sel])
            X_test_full = np.hstack([X_test_clin, X_test_rna_sel, X_test_cnv_sel])

            model_full = CoxnetSurvivalAnalysis(
                l1_ratio=0.9,
                alpha_min_ratio=0.01,
                max_iter=100000,
                fit_baseline_model=True,
            )
            model_full.fit(X_train_full, y_train)
            full_test_c = model_full.score(X_test_full, y_test)

            selected_rna_names = [rna_cols[i] for i in top_rna_idx]
            selected_cnv_names = [cnv_cols[i] for i in top_cnv_idx]
            n_rna_priority_actual = len(selected_rna_names)
            n_scna_priority_actual = len(selected_cnv_names)

            print(f"    Clinical+RNA+SCNA{n_scna_priority} Test C-index: {full_test_c:.4f}")

            results.append({
                "Experiment": "Priority_Lasso",
                "Config": f"RNA{n_rna_priority_actual}_SCNA{n_scna_priority_actual}",
                "N_Clinical": len(clin_names),
                "N_RNA": n_rna_priority_actual,
                "N_SCNA": n_scna_priority_actual,
                "N_Total": len(clin_names) + n_rna_priority_actual + n_scna_priority_actual,
                "OOB_C": np.nan,
                "Train_C": model_full.score(X_train_full, y_train),
                "Test_C": full_test_c,
            })

            all_models[f"PriorityLasso_RNA{n_rna_priority_actual}_SCNA{n_scna_priority_actual}"] = {
                "model": model_full,
                "X_test": X_test_full,
                "features": clin_names + selected_rna_names + selected_cnv_names,
                "rna_features": selected_rna_names,
                "scna_features": selected_cnv_names,
            }

        except Exception as e:
            print(f"    Full model failed with SCNA{n_scna_priority}: {e}")

    # Experiment 3: Late Fusion Ensemble
    print("\n" + "=" * 70)
    print("Experiment 3: Late Fusion Ensemble")
    print("=" * 70)
    print("  Strategy: Separate RSF_RNA + RSF_SCNA, weighted ensemble")

    # Model A: Clinical + RNA (like v6 best)
    print("\n  Training RSF_RNA (Clinical + 75 RNA)...")
    n_rna_fusion = 75
    top_rna_idx_fusion = top_feature_indices(rna_scores, n_rna_fusion)
    X_train_rna_fusion = np.hstack([X_train_clin, X_train_rna_scaled[:, top_rna_idx_fusion]])
    X_test_rna_fusion = np.hstack([X_test_clin, X_test_rna_scaled[:, top_rna_idx_fusion]])

    model_rna_rsf, params_rna = tune_rsf_aggressive(X_train_rna_fusion, y_train, args.n_jobs, args.seed)
    if model_rna_rsf:
        test_c_rna = model_rna_rsf.score(X_test_rna_fusion, y_test)
        print(f"    RSF_RNA Test C-index: {test_c_rna:.4f}")
        pred_rna_train_fusion = model_rna_rsf.predict(X_train_rna_fusion)
        pred_rna_fusion = model_rna_rsf.predict(X_test_rna_fusion)
    else:
        print("    RSF_RNA failed")
        test_c_rna = 0.5
        pred_rna_train_fusion = np.zeros(len(train_df))
        pred_rna_fusion = np.zeros(len(test_df))

    # Model B: Clinical + SCNA
    print("\n  Training RSF_SCNA (Clinical + 20 SCNA)...")
    n_cnv_fusion = 20
    top_cnv_idx_fusion = top_feature_indices(cnv_scores, n_cnv_fusion)
    X_train_cnv_fusion = np.hstack([X_train_clin, X_train_cnv_scaled[:, top_cnv_idx_fusion]])
    X_test_cnv_fusion = np.hstack([X_test_clin, X_test_cnv_scaled[:, top_cnv_idx_fusion]])

    model_cnv_rsf, params_cnv = tune_rsf_aggressive(X_train_cnv_fusion, y_train, args.n_jobs, args.seed)
    if model_cnv_rsf:
        test_c_cnv = model_cnv_rsf.score(X_test_cnv_fusion, y_test)
        print(f"    RSF_SCNA Test C-index: {test_c_cnv:.4f}")
        pred_cnv_train_fusion = model_cnv_rsf.predict(X_train_cnv_fusion)
        pred_cnv_fusion = model_cnv_rsf.predict(X_test_cnv_fusion)
    else:
        print("    RSF_SCNA failed")
        test_c_cnv = 0.5
        pred_cnv_train_fusion = np.zeros(len(train_df))
        pred_cnv_fusion = np.zeros(len(test_df))

    def normalize_with_train(train_pred, test_pred):
        center = train_pred.mean()
        scale = train_pred.std() + 1e-10
        return (train_pred - center) / scale, (test_pred - center) / scale

    pred_rna_train_norm, pred_rna_norm = normalize_with_train(
        pred_rna_train_fusion, pred_rna_fusion
    )
    pred_cnv_train_norm, pred_cnv_norm = normalize_with_train(
        pred_cnv_train_fusion, pred_cnv_fusion
    )

    # Choose the fusion weight on training predictions, then report the locked
    # weight on CPTAC. This avoids using the external validation cohort to tune
    # the ensemble weight.
    print("\n  Testing fusion weights...")
    best_fusion_train_c = 0
    best_fusion_c = 0
    best_alpha = 0

    for alpha in [0.95, 0.9, 0.85, 0.8, 0.75, 0.7]:
        pred_fusion_train = alpha * pred_rna_train_norm + (1 - alpha) * pred_cnv_train_norm
        train_fusion_c, _, _, _, _ = concordance_index_censored(
            y_train["event"], y_train["time"], pred_fusion_train
        )
        pred_fusion = alpha * pred_rna_norm + (1 - alpha) * pred_cnv_norm
        fusion_c, _, _, _, _ = concordance_index_censored(
            y_test["event"], y_test["time"], pred_fusion
        )
        print(
            f"    α={alpha:.2f} (RNA={alpha:.0%}, SCNA={1-alpha:.0%}): "
            f"Train C = {train_fusion_c:.4f}, Test C = {fusion_c:.4f}"
        )

        if train_fusion_c > best_fusion_train_c:
            best_fusion_train_c = train_fusion_c
            best_fusion_c = fusion_c
            best_alpha = alpha

    print(
        f"\n  Best fusion by training C-index: α={best_alpha:.2f}, "
        f"Train C-index: {best_fusion_train_c:.4f}, Test C-index: {best_fusion_c:.4f}"
    )

    selected_rna_fusion = [rna_cols[i] for i in top_rna_idx_fusion]
    selected_cnv_fusion = [cnv_cols[i] for i in top_cnv_idx_fusion]
    n_rna_fusion_actual = len(selected_rna_fusion)
    n_cnv_fusion_actual = len(selected_cnv_fusion)

    results.append({
        "Experiment": "Late_Fusion",
        "Config": f"RNA{n_rna_fusion_actual}_SCNA{n_cnv_fusion_actual}_alpha{best_alpha:.2f}",
        "N_Clinical": len(clin_names),
        "N_RNA": n_rna_fusion_actual,
        "N_SCNA": n_cnv_fusion_actual,
        "N_Total": len(clin_names) + n_rna_fusion_actual + n_cnv_fusion_actual,
        "OOB_C": np.nan,
        "Train_C": best_fusion_train_c,
        "Test_C": best_fusion_c,
    })

    all_models[f"LateFusion_alpha{best_alpha:.2f}"] = {
        "model": (model_rna_rsf, model_cnv_rsf),
        "X_test": (X_test_rna_fusion, X_test_cnv_fusion),
        "features": clin_names + selected_rna_fusion + selected_cnv_fusion,
        "rna_features": selected_rna_fusion,
        "scna_features": selected_cnv_fusion,
        "alpha": best_alpha,
    }

    # Experiment 4: IPF-LASSO Style (Different Penalties)
    print("\n" + "=" * 70)
    print("Experiment 4: IPF-LASSO Style (Different Regularization per Block)")
    print("=" * 70)
    print("  Strategy: Lower penalty on SCNA to encourage inclusion")

    # Implement via feature scaling: multiply SCNA features by a factor
    # to effectively reduce their penalty
    for scna_boost in [2.0, 1.5, 1.25]:
        print(f"\n  [SCNA boost factor: {scna_boost}x]")

        n_rna_ipf = 60
        n_cnv_ipf = 10

        top_rna_idx_ipf = top_feature_indices(rna_scores, n_rna_ipf)
        top_cnv_idx_ipf = top_feature_indices(cnv_scores, n_cnv_ipf)

        # Boost SCNA features
        X_train_cnv_boosted = X_train_cnv_scaled[:, top_cnv_idx_ipf] * scna_boost
        X_test_cnv_boosted = X_test_cnv_scaled[:, top_cnv_idx_ipf] * scna_boost

        X_train_ipf = np.hstack([
            X_train_clin,
            X_train_rna_scaled[:, top_rna_idx_ipf],
            X_train_cnv_boosted
        ])
        X_test_ipf = np.hstack([
            X_test_clin,
            X_test_rna_scaled[:, top_rna_idx_ipf],
            X_test_cnv_boosted
        ])

        # Use RSF (more robust than CoxNet for this)
        model_ipf, params_ipf = tune_rsf_aggressive(X_train_ipf, y_train, args.n_jobs, args.seed)

        if model_ipf:
            test_c_ipf = model_ipf.score(X_test_ipf, y_test)
            print(f"    Test C-index: {test_c_ipf:.4f}")

            selected_rna_ipf = [rna_cols[i] for i in top_rna_idx_ipf]
            selected_cnv_ipf = [cnv_cols[i] for i in top_cnv_idx_ipf]
            n_rna_ipf_actual = len(selected_rna_ipf)
            n_cnv_ipf_actual = len(selected_cnv_ipf)

            results.append({
                "Experiment": "IPF_Style",
                "Config": f"RNA{n_rna_ipf_actual}_SCNA{n_cnv_ipf_actual}_boost{scna_boost}",
                "N_Clinical": len(clin_names),
                "N_RNA": n_rna_ipf_actual,
                "N_SCNA": n_cnv_ipf_actual,
                "N_Total": len(clin_names) + n_rna_ipf_actual + n_cnv_ipf_actual,
                "OOB_C": model_ipf.oob_score_,
                "Train_C": model_ipf.score(X_train_ipf, y_train),
                "Test_C": test_c_ipf,
            })

            all_models[f"IPF_boost{scna_boost}"] = {
                "model": model_ipf,
                "X_test": X_test_ipf,
                "features": clin_names + selected_rna_ipf + selected_cnv_ipf,
                "rna_features": selected_rna_ipf,
                "scna_features": selected_cnv_ipf,
            }

    if args.mode == "extended":
        print("\nSkipping bootstrap stability selection; use --mode full to run it.")
        write_model_outputs(
            output_dir,
            results,
            all_models,
            clin_names,
            rna_cols,
            cnv_cols,
            rna_scores,
            cnv_scores,
        )
        return

    # Experiment 5: Stability-Selected Multi-Block
    print("\n" + "=" * 70)
    print("Experiment 5: Stability-Selected Multi-Block")
    print("=" * 70)
    print("  Strategy: Bootstrap selection on RNA and SCNA separately")

    # Stability selection on RNA
    print("\n  Running stability selection on RNA (100 bootstraps)...")
    rna_stability = stability_selection_per_block(
        X_train_rna_scaled, y_train, n_bootstrap=100, top_k=50, seed=args.seed
    )
    stable_rna_idx = np.where(rna_stability >= 0.5)[0]
    print(f"    RNA features with >50% stability: {len(stable_rna_idx)}")

    # Stability selection on SCNA
    print("\n  Running stability selection on SCNA (100 bootstraps)...")
    cnv_stability = stability_selection_per_block(
        X_train_cnv_scaled, y_train, n_bootstrap=100, top_k=20, seed=args.seed
    )
    stable_cnv_idx = np.where(cnv_stability >= 0.3)[0]  # Lower threshold for SCNA
    print(f"    SCNA features with >30% stability: {len(stable_cnv_idx)}")

    # Ensure minimum 4 SCNA
    if len(stable_cnv_idx) < 4:
        print(f"    Less than 4 stable SCNA, using top 4 by stability probability")
        stable_cnv_idx = top_feature_indices(cnv_stability, 4)

    # If too few stable RNA, use top by C-index
    if len(stable_rna_idx) < 30:
        print(f"    Less than 30 stable RNA, using top 50 by C-index")
        stable_rna_idx = top_feature_indices(rna_scores, 50)

    # Combine stable features
    X_train_stable = np.hstack([
        X_train_clin,
        X_train_rna_scaled[:, stable_rna_idx],
        X_train_cnv_scaled[:, stable_cnv_idx]
    ])
    X_test_stable = np.hstack([
        X_test_clin,
        X_test_rna_scaled[:, stable_rna_idx],
        X_test_cnv_scaled[:, stable_cnv_idx]
    ])

    selected_rna_stable = [rna_cols[i] for i in stable_rna_idx]
    selected_cnv_stable = [cnv_cols[i] for i in stable_cnv_idx]

    print(f"\n  Training RSF with {len(stable_rna_idx)} stable RNA + {len(stable_cnv_idx)} stable SCNA...")

    model_stable, params_stable = tune_rsf_aggressive(X_train_stable, y_train, args.n_jobs, args.seed)

    if model_stable:
        test_c_stable = model_stable.score(X_test_stable, y_test)
        print(f"    Test C-index: {test_c_stable:.4f}")

        results.append({
            "Experiment": "Stability_MultiBlock",
            "Config": f"RNA{len(stable_rna_idx)}_SCNA{len(stable_cnv_idx)}",
            "N_Clinical": len(clin_names),
            "N_RNA": len(stable_rna_idx),
            "N_SCNA": len(stable_cnv_idx),
            "N_Total": len(clin_names) + len(stable_rna_idx) + len(stable_cnv_idx),
            "OOB_C": model_stable.oob_score_,
            "Train_C": model_stable.score(X_train_stable, y_train),
            "Test_C": test_c_stable,
        })

        all_models["Stability_MultiBlock"] = {
            "model": model_stable,
            "X_test": X_test_stable,
            "features": clin_names + selected_rna_stable + selected_cnv_stable,
            "rna_features": selected_rna_stable,
            "scna_features": selected_cnv_stable,
        }

    # SUMMARY
    print("\n" + "=" * 70)
    print("FINAL RESULTS")
    print("=" * 70)

    results_df = pd.DataFrame(results)
    if results_df.empty:
        print("No models completed successfully; writing empty results table.")
        results_df.to_csv(os.path.join(output_dir, "all_results.csv"), index=False)
        return
    results_df = results_df.sort_values("Test_C", ascending=False)

    print("\n--- ALL RESULTS (sorted by Test C-index) ---")
    print(results_df.to_string(index=False))

    # Find best model meeting both criteria
    print("\n" + "-" * 50)
    print("Promising Models are defined as:")
    print("  (Test C-index >= 0.65)")
    print("-" * 50)

    qualifying_models = results_df[
        (results_df["N_SCNA"] >= 4) & (results_df["Test_C"] >= 0.6448)
    ]

    if len(qualifying_models) > 0:
        print(qualifying_models.to_string(index=False))
        best = qualifying_models.iloc[0]
        print(f"\n🎯 BEST MODEL: {best['Experiment']} ({best['Config']})")
        print(f"   Test C-index: {best['Test_C']:.4f}")
        print(f"   Features: {best['N_Clinical']} clinical + {best['N_RNA']} RNA + {best['N_SCNA']} SCNA")

        if best["Test_C"] >= 0.65:
            print("\nTarget Achieved! Test C-index >= 0.65")
        else:
            gap = 0.65 - best["Test_C"]
            print(f"\n Gap to 0.65 target: {gap:.4f}")
    else:
        print("\nNo models met both criteria (>=4 SCNA and >=0.6448 C-index)")
        print("   Best overall model:")
        best = results_df.iloc[0]
        print(f"   {best['Experiment']} ({best['Config']}): Test C = {best['Test_C']:.4f}, {best['N_SCNA']} SCNA")

    # Save results
    results_df.to_csv(os.path.join(output_dir, "all_results.csv"), index=False)

    # Save feature lists for the selected model. If no model meets the hard
    # success criteria, still save the best overall model so downstream
    # enrichment has a real feature table to consume.
    selected_summary_row = qualifying_models.iloc[0] if len(qualifying_models) > 0 else results_df.iloc[0]

    def infer_model_key(row):
        experiment = row["Experiment"]
        config = row["Config"]
        if experiment == "Block_Constrained":
            return f"Block_{config}"
        if experiment == "Priority_Lasso":
            return f"PriorityLasso_{config}"
        if experiment == "Late_Fusion":
            return f"LateFusion_alpha{str(config).split('alpha')[-1]}"
        if experiment == "IPF_Style":
            return f"IPF_boost{str(config).split('boost')[-1]}"
        if experiment == "Stability_MultiBlock":
            return "Stability_MultiBlock"
        return None

    best_key = infer_model_key(selected_summary_row)
    if best_key not in all_models:
        print(f"Warning: could not find stored model for feature export: {best_key}")
    else:
        best_model_info = all_models[best_key]
        feature_df = pd.DataFrame({
            "feature": best_model_info["features"],
            "type": ["clinical"] * len(clin_names)
                    + ["RNA"] * len(best_model_info["rna_features"])
                    + ["SCNA"] * len(best_model_info["scna_features"]),
        })
        feature_df.to_csv(os.path.join(output_dir, "best_model_features.csv"), index=False)

        rna_feature_df = pd.DataFrame({
            "feature": best_model_info["rna_features"],
            "cindex_deviation": [rna_scores[rna_cols.index(f)] for f in best_model_info["rna_features"]],
        }).sort_values("cindex_deviation", ascending=False)
        rna_feature_df.to_csv(os.path.join(output_dir, "selected_rna_features.csv"), index=False)

        scna_feature_df = pd.DataFrame({
            "feature": best_model_info["scna_features"],
            "cindex_deviation": [cnv_scores[cnv_cols.index(f)] for f in best_model_info["scna_features"]],
        }).sort_values("cindex_deviation", ascending=False)
        scna_feature_df.to_csv(os.path.join(output_dir, "selected_scna_features.csv"), index=False)

        print(f"\nFeature lists saved to: {output_dir}")

    # Save top SCNA features for reference
    top_scna_indices = top_feature_indices(cnv_scores, 20)
    top_scna_df = pd.DataFrame({
        "feature": [cnv_cols[i] for i in top_scna_indices],
        "cindex_deviation": [cnv_scores[i] for i in top_scna_indices],
        "stability": [cnv_stability[i] for i in top_scna_indices],
    })
    top_scna_df.to_csv(os.path.join(output_dir, "top20_scna_features.csv"), index=False)

    print(f"\nResults saved to: {output_dir}")


if __name__ == "__main__":
    main()
